# Generated by Django 3.0.5 on 2020-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='LinkedIn Id')),
                ('first_name', models.CharField(max_length=30, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=30, verbose_name='LastName')),
                ('profile_pic_url', models.CharField(max_length=100, null=True, verbose_name='Profile Picture')),
            ],
        ),
    ]
